import recentItemOne from '../../assets/images/recentItem1.png';
import recentItemTwo from '../../assets/images/recentItem-2.png';
import recentItemThree from '../../assets/images/recentItem-3.png';
import recentItemFour from '../../assets/images/recentItem-4.png';
import recentItemFive from '../../assets/images/recentItem-5.png';
import recentItemSix from '../../assets/images/recentItem-6.png';
import productImage1 from '../../assets/images/productImage1.png';
import productImage2 from '../../assets/images/productImage2.png';
import productImage3 from '../../assets/images/productImage3.png';
import productImage4 from '../../assets/images/productImage4.png';

export const catalogItems = [
  {
    title: 'Veggie Wax Candle Table',
    titleUkr: 'Свічка з бджолиного воску',
    reviews: 44,
    price: 2429,
    discount: 350,
    inStock: true,
    rate: 1,
    sizes: [20, 40],
    similar: [2, 3],
    videoLink: 'https://www.youtube.com',
    products: [
      {
        price: 2429,
        discount: 350,
        color: '#C84A1E',
        images: [productImage1, productImage1],
        alt: 'brown sofa',
        label: 'sale',
      },
      {
        price: 2529,
        discount: 350,
        color: '#FFE83E',
        images: [productImage2, productImage2],
        alt: 'yellow sofa',
        label: 'new',
      },
    ],
    id: 1,
  },
  {
    title: 'Meggie Wax Candle Res',
    titleUkr: 'Свічка з бджолиного воску',
    reviews: 44,
    price: 5000,
    discount: 400,
    inStock: true,
    rate: 5,
    sizes: [20, 40],
    similar: [1, 3, 5],
    videoLink: 'https://www.youtube.com',
    products: [
      {
        price: 5000,
        discount: 400,
        color: '#9fa2a6',
        images: [productImage3, productImage3],
        alt: 'brown sofa',
        label: 'sale',
      },
      {
        price: 4000,
        discount: 900,
        color: '#ffa800',
        images: [productImage4, productImage4],
        alt: 'yellow sofa',
        label: 'new',
      },
    ],
    id: 2,
  },
  {
    title: 'Ceggie Wax Candle Table Op',
    titleUkr: 'Свічка з бджолиного воску',
    reviews: 44,
    price: 6000,
    discount: 950,
    inStock: true,
    rate: 3,
    sizes: [20, 40],
    similar: [2, 3],
    videoLink: 'https://www.youtube.com',
    products: [
      {
        price: 6000,
        discount: 950,
        color: '#C84A1E',
        images: [recentItemThree, recentItemThree],
        alt: 'brown sofa',
        label: 'sale',
      },
      {
        price: 3000,
        discount: 950,
        color: '#FFE83E',
        images: [recentItemFive, recentItemFive],
        alt: 'yellow sofa',
        label: 'popular',
      },
    ],
    id: 3,
  },
  {
    title: 'Leggie Wax Candle Table Lol',
    titleUkr: 'Свічка з бджолиного воску',
    reviews: 44,
    price: 7000,
    discount: 650,
    inStock: true,
    rate: 4,
    sizes: [20, 40],
    similar: [2, 3],
    videoLink: 'https://www.youtube.com',
    products: [
      {
        price: 7000,
        discount: 650,
        color: '#C84A1E',
        images: [productImage1, productImage1],
        alt: 'brown sofa',
        label: 'sale',
      },
      {
        price: 7500,
        discount: 650,
        color: '#FFE83E',
        images: [recentItemTwo, recentItemTwo],
        alt: 'yellow sofa',
        label: 'new',
      },
    ],
    id: 4,
  },
  {
    title: 'Peggie Wax Candle Table Spruce Resin',
    titleUkr: 'Свічка з бджолиного воску',
    reviews: 44,
    price: 6500,
    discount: 100,
    inStock: true,
    rate: 4,
    sizes: [20, 40],
    similar: [2, 3],
    videoLink: 'https://www.youtube.com',
    products: [
      {
        price: 6500,
        discount: 100,
        color: '#C84A1E',
        images: [productImage2, productImage2],
        alt: 'brown sofa',
        label: 'sale',
      },
      {
        price: 6300,
        discount: 100,
        color: '#FFE83E',
        images: [recentItemTwo, recentItemTwo],
        alt: 'yellow sofa',
        label: 'new',
      },
    ],
    id: 5,
  },
  {
    title: 'Teggie Wax Candle',
    titleUkr: 'Свічка з бджолиного воску',
    reviews: 44,
    price: 7400,
    discount: 700,
    inStock: true,
    rate: 5,
    sizes: [20, 40],
    similar: [2, 3],
    videoLink: 'https://www.youtube.com',
    products: [
      {
        price: 7400,
        discount: 700,
        color: '#C84A1E',
        images: [productImage4, productImage4],
        alt: 'brown sofa',
        label: 'sale',
      },
      {
        price: 8000,
        discount: 700,
        color: '#FFE83E',
        images: [recentItemTwo, recentItemTwo],
        alt: 'yellow sofa',
        label: 'new',
      },
    ],
    id: 6,
  },
  {
    title: 'Beggie Wax Candle Table',
    titleUkr: 'Свічка з бджолиного воску',
    reviews: 44,
    price: 7500,
    discount: '',
    inStock: true,
    rate: 1,
    sizes: [20, 40],
    similar: [2, 3],
    videoLink: 'https://www.youtube.com',
    products: [
      {
        price: 7500,
        discount: '',
        color: '#C84A1E',
        images: [recentItemTwo, recentItemTwo],
        alt: 'brown sofa',
        label: 'sale',
      },
      {
        price: 7900,
        discount: '',
        color: '#FFE83E',
        images: [productImage4, productImage4],
        alt: 'yellow sofa',
        label: 'new',
      },
    ],
    id: 7,
  },
  {
    title: 'Zeggie Wax Candle Table',
    titleUkr: 'Свічка з бджолиного воску',
    reviews: 44,
    price: 7300,
    discount: 100,
    inStock: true,
    rate: 2,
    sizes: [20, 40],
    similar: [2, 3, 4, 5],
    videoLink: 'https://www.youtube.com',
    products: [
      {
        price: 7300,
        discount: 100,
        color: '#C84A1E',
        images: [recentItemSix, recentItemSix],
        alt: 'brown sofa',
        label: 'sale',
      },
      {
        price: 7900,
        discount: 500,
        color: '#FFE83E',
        images: [recentItemTwo, recentItemTwo],
        alt: 'yellow sofa',
        label: 'new',
      },
    ],
    id: 8,
  },
  {
    title: 'Neggie Wax Candle Table',
    titleUkr: 'Свічка з бджолиного воску',
    reviews: 44,
    price: 9999,
    discount: 3000,
    inStock: true,
    rate: 3,
    sizes: [20, 40],
    similar: [2, 3, 4, 5],
    videoLink: 'https://www.youtube.com',
    products: [
      {
        price: 9999,
        discount: 3000,
        color: '#C84A1E',
        images: [recentItemFive, recentItemFive],
        alt: 'brown sofa',
        label: 'sale',
      },
      {
        price: 9999,
        discount: 4000,
        color: '#FFE83E',
        images: [recentItemTwo, recentItemTwo],
        alt: 'yellow sofa',
        label: 'new',
      },
    ],
    id: 9,
  },
  {
    title: 'Seggie Wax Candle Table',
    titleUkr: 'Свічка з бджолиного воску',
    reviews: 44,
    price: 10100,
    discount: 3000,
    inStock: true,
    rate: 3,
    sizes: [20, 40],
    similar: [2, 3, 4, 5],
    videoLink: 'https://www.youtube.com',
    products: [
      {
        price: 10100,
        discount: 3000,
        color: '#C84A1E',
        images: [recentItemThree, recentItemThree],
        alt: 'brown sofa',
        label: 'sale',
      },
      {
        price: 9100,
        discount: 3000,
        color: '#FFE83E',
        images: [recentItemTwo, recentItemTwo],
        alt: 'yellow sofa',
        label: 'new',
      },
    ],
    id: 10,
  },
  {
    title: 'Feggie Wax Candle Table',
    titleUkr: 'Свічка з бджолиного воску',
    reviews: 44,
    price: 10500,
    discount: 2000,
    inStock: true,
    rate: 2,
    sizes: [20, 40],
    similar: [2, 3, 4, 5],
    videoLink: 'https://www.youtube.com',
    products: [
      {
        price: 10500,
        discount: 2000,
        color: '#C84A1E',
        images: [recentItemOne, recentItemOne],
        alt: 'brown sofa',
        label: 'sale',
      },
      {
        price: 10000,
        discount: 2000,
        color: '#FFE83E',
        images: [recentItemTwo, recentItemTwo],
        alt: 'yellow sofa',
        label: 'new',
      },
    ],
    id: 11,
  },
  {
    title: 'Xeggie Wax Candle Table',
    titleUkr: 'Свічка з бджолиного воску',
    reviews: 44,
    price: 10200,
    discount: 1000,
    inStock: true,
    rate: 1,
    sizes: [20, 40],
    similar: [2, 3, 4, 5],
    videoLink: 'https://www.youtube.com',
    products: [
      {
        price: 10200,
        discount: 1000,
        color: '#C84A1E',
        images: [recentItemFour, recentItemFour],
        alt: 'brown sofa',
        label: 'sale',
      },
      {
        price: 10200,
        discount: 6000,
        color: '#FFE83E',
        images: [recentItemTwo, recentItemTwo],
        alt: 'yellow sofa',
        label: 'new',
      },
    ],
    id: 12,
  },
  {
    title: 'Ceggie Wax Candle Table',
    titleUkr: 'Свічка з бджолиного воску',
    reviews: 44,
    price: 10199,
    discount: '',
    inStock: true,
    rate: 1,
    sizes: [20, 40],
    similar: [2, 3, 4, 5],
    videoLink: 'https://www.youtube.com',
    products: [
      {
        price: 10199,
        discount: '',
        color: '#C84A1E',
        images: [recentItemThree, recentItemThree],
        alt: 'brown sofa',
        label: 'sale',
      },
      {
        price: 8199,
        discount: '',
        color: '#FFE83E',
        images: [recentItemFour, recentItemFour],
        alt: 'yellow sofa',
        label: 'new',
      },
    ],
    id: 13,
  },
  {
    title: 'Weggie Wax Candle Table',
    titleUkr: 'Свічка з бджолиного воску',
    reviews: 44,
    price: 10100,
    discount: '',
    inStock: true,
    rate: 5,
    sizes: [20, 40],
    similar: [2, 3, 4, 5],
    videoLink: 'https://www.youtube.com',
    products: [
      {
        price: 10100,
        discount: '',
        color: '#C84A1E',
        images: [recentItemThree, recentItemThree],
        alt: 'brown sofa',
        label: 'sale',
      },
      {
        price: 9100,
        discount: '',
        color: '#FFE83E',
        images: [recentItemFour, recentItemFour],
        alt: 'yellow sofa',
        label: 'new',
      },
    ],
    id: 14,
  },
  {
    title: 'Qeggie Wax Candle Table',
    titleUkr: 'Свічка з бджолиного воску',
    reviews: 44,
    price: 10900,
    discount: '',
    inStock: true,
    rate: 5,
    sizes: [20, 40],
    similar: [2, 3, 4, 5],
    videoLink: 'https://www.youtube.com',
    products: [
      {
        price: 10900,
        discount: '',
        color: '#C84A1E',
        images: [recentItemFour, recentItemFour],
        alt: 'brown sofa',
        label: 'sale',
      },
      {
        price: 10000,
        discount: '',
        color: '#FFE83E',
        images: [recentItemThree, recentItemThree],
        alt: 'yellow sofa',
        label: 'new',
      },
    ],
    id: 15,
  },
];
