import productOne from '../../assets/images/productImage1.png';
import productTwo from '../../assets/images/productImage2.png';

export const productItems = [
  {
    title: 'Veggie Wax Candle Table',
    titleUkr: 'Свічка з бджолиного воску',
    reviews: 44,
    price: 5000,
    discount: 350,
    inStock: true,
    rate: 4,
    sizes: [20, 40],
    videoLink: 'https://www.youtube.com',
    products: [
      {
        price: 2429,
        discount: 350,
        color: '#C84A1E',
        images: [productOne, productOne],
        alt: 'brown sofa',
        label: 'sale',
      },
      {
        price: 2529,
        discount: 350,
        color: '#FFE83E',
        images: [productTwo],
        alt: 'yellow sofa',
        label: 'new',
      },
    ],
    similar: [2, 3],
    id: 1,
  },
  {
    title: 'Veggie Wax Candle Table',
    titleUkr: 'Свічка з бджолиного воску',
    reviews: 44,
    price: 5000,
    discount: 350,
    inStock: true,
    rate: 4,
    sizes: [20, 40],
    videoLink: 'https://www.youtube.com',
    products: [
      {
        price: 2429,
        discount: 350,
        color: '#C84A1E',
        images: [productOne, productOne],
        alt: 'brown sofa',
        label: 'sale',
      },
      {
        price: 2529,
        discount: 350,
        color: '#FFE83E',
        images: [productTwo],
        alt: 'yellow sofa',
        label: 'new',
      },
    ],
    id: 2,
  },
  {
    title: 'Veggie Wax Candle Table',
    titleUkr: 'Свічка з бджолиного воску',
    reviews: 44,
    price: 5000,
    discount: 350,
    inStock: true,
    rate: 4,
    sizes: [20, 40],
    videoLink: 'https://www.youtube.com',
    products: [
      {
        price: 2429,
        discount: 350,
        color: '#C84A1E',
        images: [productOne, productOne],
        alt: 'brown sofa',
        label: 'sale',
      },
      {
        price: 2529,
        discount: 350,
        color: '#FFE83E',
        images: [productTwo],
        alt: 'yellow sofa',
        label: 'popular',
      },
    ],
    id: 3,
  },
  {
    title: 'Veggie Wax Candle No disc',
    titleUkr: 'Свічка з бджолиного воску',
    reviews: 44,
    price: 4000,
    inStock: true,
    rate: 4,
    sizes: [20, 40],
    videoLink: 'https://www.youtube.com',
    products: [
      {
        price: 2429,
        discount: 350,
        color: '#C84A1E',
        images: [productOne, productOne],
        alt: 'brown sofa',
        label: 'sale',
      },
      {
        price: 2529,
        discount: 350,
        color: '#FFE83E',
        images: [productTwo],
        alt: 'yellow sofa',
        label: 'new',
      },
    ],
    id: 4,
  },
];
